spring:
  application:
    name: practical_train_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.194.188:3306/practical_train?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: remote_user
    password: remote_password

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
